name: Anchorage Real Estate Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.8577577532269061
  saturation: 0.5
  rhythmicContrast: 0.7464568703435361
purpose: []
